### ISSUE TITLE
[Bug] AvatarChatbot can NOT work in K8s environment because of functional gap in wav2clip service

### ISSUE THREAD

**Issue by lianhao** [opea-project/GenAIExamples#1506]
### Priority

P1-Stopper

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Installation method

- [x] Pull docker images from hub.docker.com
- [ ] Build docker images from source
- [ ] Other

### Deploy method

- [ ] Docker
- [x] Docker Compose
- [ ] Kubernetes Helm Charts
- [ ] Kubernetes GMC
- [x] Other

### Running nodes

Single Node

### What's the version?

git commit 45d5da2

### Description

The current AvatarChatbot example requires the users to map a local disk directory for the `wav2clip` service to save the result, i.e. see the `volumes` section in the following docker compose file definition:

```
wav2lip-service:
    image: ${REGISTRY:-opea}/wav2lip:${TAG:-latest}
    container_name: wav2lip-service
    ports:
      - "7860:7860"
    ipc: host
    volumes:
      - ${PWD}:/outputs
    ... ...
```

The user will need to read files from the current local directory of `{PWD}` to get the results. This kind of requirement prohibits us to deploy the AvatarChatBot in Kubernetes(K8s) environment, where the `wav2clip` service could be scheduled to one of the node in the k8s cluster which the end user will never have access to.

The `wav2clip` service need to return the generated file content, instead of just returning the filename.

### Reproduce steps

n/a

### Raw log

```shell

```
