### ISSUE TITLE
[Bug]CodeGen React UI does not respond

### ISSUE THREAD

**Issue by xiguiw** [opea-project/GenAIExamples#806]
### Priority

P2-High

### OS type

Ubuntu

### Hardware type

Xeon-GNR

### Installation method

- [X] Pull docker images from hub.docker.com
- [ ] Build docker images from source

### Deploy method

- [X] Docker compose
- [ ] Docker
- [ ] Kubernetes
- [ ] Helm

### Running nodes

Single Node

### What's the version?

docker latest

### Description

CodeGen React UI does not respond (CodeGen UI works as expected)
![image](https://github.com/user-attachments/assets/6d350811-2e07-42cb-859f-c34d0ac12fe0)

### Reproduce steps

docker compose -f ./compose.yaml up -d

compose.yaml contents:
```
# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  tgi-service:
    image: ghcr.io/huggingface/text-generation-inference:sha-e4201f4-intel-cpu
    container_name: tgi-service
    ports:
      - "8028:80"
    volumes:
      - "./data:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HF_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
    command: --model-id ${LLM_MODEL_ID} --cuda-graphs 0
  llm:
    image: ${REGISTRY:-opea}/llm-tgi:${TAG:-latest}
    container_name: llm-tgi-server
    depends_on:
      - tgi-service
    ports:
      - "9000:9000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      TGI_LLM_ENDPOINT: ${TGI_LLM_ENDPOINT}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
    restart: unless-stopped
  codegen-xeon-backend-server:
    image: ${REGISTRY:-opea}/codegen:${TAG:-latest}
    container_name: codegen-xeon-backend-server
    depends_on:
      - llm
    ports:
      - "7778:7778"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - MEGA_SERVICE_HOST_IP=${MEGA_SERVICE_HOST_IP}
      - LLM_SERVICE_HOST_IP=${LLM_SERVICE_HOST_IP}
    ipc: host
    restart: always
  codegen-xeon-react-ui-server:
    image: ${REGISTRY:-opea}/codegen-react-ui:latest
    container_name: codegen-xeon-react-ui-server
    depends_on:
      - codegen-xeon-backend-server
    ports:
      - "5174:80"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
    ipc: host
    restart: always

networks:
  default:
    driver: bridge
```

### Raw log

```shell
CodeGen React UI does not respond (CodeGen UI works as expected)
```
